In [3]:
import pandas as pd
import numpy as np

In [4]:
file = '..//data//nsduh_reduced.csv'
main_data = pd.read_csv(file, sep=',')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x = main_data.drop('CATEGORY',axis=1)
y = main_data['CATEGORY']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=121)

In [7]:
df_train = pd.DataFrame(y_train)
df_train.groupby('CATEGORY').groups

{0: Int64Index([44430, 12595, 22049, 44109, 54722, 19345, 18298, 41801, 38675,
             17793,
             ...
              4391,  8678, 48111, 32820, 33716, 19198, 30754, 36351, 37333,
             11586],
            dtype='int64', length=15619),
 1: Int64Index([51587, 47581, 42403, 12862, 14754, 14676, 28945,  6922, 52089,
             31177,
             ...
              9523, 30558, 25399,  7225, 44547, 22582, 29280, 24915, 54964,
             28148],
            dtype='int64', length=13631),
 2: Int64Index([53020,  9654, 37439, 26126, 39541, 32172, 50856, 41209,  6069,
              8217,
             ...
             49037, 22388, 29651,  9944,  1099,  4073, 31710, 43068, 26670,
             51265],
            dtype='int64', length=10143)}

In [8]:
df_test = pd.DataFrame(y_test)
df_test.groupby('CATEGORY').groups

{0: Int64Index([15799, 56103,  1467, 34251, 19068, 18303,   923, 14793, 30893,
             14536,
             ...
             28425, 22669, 17998, 33849, 12126, 54186,  9210,  4956, 21587,
             21983],
            dtype='int64', length=6682),
 1: Int64Index([ 9775, 37099, 37773,  8448,  3983,  9358, 43563, 41980, 38819,
             43761,
             ...
             53560,   263, 23343, 40054, 40423, 15142, 44357, 48249, 55547,
              5449],
            dtype='int64', length=5836),
 2: Int64Index([48808,  4933,  9854, 25010, 37427, 18427, 45253, 48709, 48191,
             29866,
             ...
             16669, 51597, 20009,  5990, 36641, 25520, 30348, 38952, 46361,
             36042],
            dtype='int64', length=4365)}

In [9]:
from sklearn.svm import SVC

In [10]:
svc_model = SVC()
svc_model.fit(x_train,y_train)
predictions = svc_model.predict(x_test)

C:\Users\Daria\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[2912 3770    0]
 [  18 5805   13]
 [   1 4354   10]]
              precision    recall  f1-score   support

           0       0.99      0.44      0.61      6682
           1       0.42      0.99      0.59      5836
           2       0.43      0.00      0.00      4365

   micro avg       0.52      0.52      0.52     16883
   macro avg       0.62      0.48      0.40     16883
weighted avg       0.65      0.52      0.44     16883



In [14]:
score = svc_model.score(x_test,y_test)

In [15]:
score

0.5169105016880886